"""
W1.7 — MQTT ACL rejection tests.

Each service user is allowed to publish/subscribe only to a restricted topic
set (see infra/mosquitto/aclfile).  These tests verify that a service user
*cannot* publish to a topic outside its ACL — i.e. that the broker actively
rejects unauthorised publishes.

Marker: ``@pytest.mark.integration``
Requires a live Mosquitto broker configured with the project aclfile and
passwords file.  When the broker is unreachable the test is automatically
skipped — it is safe to run in a "no-broker" CI environment.

Run integration tests:
    PYTHONPATH=services/brain/src:services/backend \\
      pytest tests/security/test_mqtt_acl.py -m integration -v

Run in-CI (skip integration):
    pytest tests/security/ -m "not integration" -v
"""

from __future__ import annotations

import os
import socket
import time
import uuid

import pytest

# ---------------------------------------------------------------------------
# Broker connection parameters (override via env vars)
# ---------------------------------------------------------------------------

MQTT_HOST = os.getenv("MQTT_HOST", "127.0.0.1")
MQTT_PORT = int(os.getenv("MQTT_PORT", "1893"))
_TIMEOUT = 5  # seconds


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _broker_reachable() -> bool:
    """Return True when a TCP connection to the broker can be established."""
    try:
        with socket.create_connection((MQTT_HOST, MQTT_PORT), timeout=3):
            return True
    except OSError:
        return False


def _skip_if_no_broker():
    """pytest.skip the calling test when the broker is not available."""
    if not _broker_reachable():
        pytest.skip(f"MQTT broker not reachable at {MQTT_HOST}:{MQTT_PORT}")


# ---------------------------------------------------------------------------
# ACL scenario table
# Each entry describes one (user, password, topic, is_publish) combination
# that SHOULD be rejected by the broker.
#
# Credentials come from infra/mosquitto/passwords (generated by setup-users.sh).
# In the test environment you can set MQTT_PASS_<USER> env vars to override.
# ---------------------------------------------------------------------------

_DEFAULT_PASSWORDS: dict[str, str] = {
    "hems-brain": os.getenv("MQTT_PASS_BRAIN", "hems_brain_dev"),
    "hems-backend": os.getenv("MQTT_PASS_BACKEND", "hems_backend_dev"),
    "hems-voice": os.getenv("MQTT_PASS_VOICE", "hems_voice_dev"),
    "hems-ha-bridge": os.getenv("MQTT_PASS_HA", "hems_ha_dev"),
    "hems-biometric": os.getenv("MQTT_PASS_BIOMETRIC", "hems_biometric_dev"),
    "hems-gas": os.getenv("MQTT_PASS_GAS", "hems_gas_dev"),
    "hems-obsidian": os.getenv("MQTT_PASS_OBSIDIAN", "hems_obsidian_dev"),
    "hems-openclaw": os.getenv("MQTT_PASS_OPENCLAW", "hems_openclaw_dev"),
    "hems-switchbot": os.getenv("MQTT_PASS_SWITCHBOT", "hems_switchbot_dev"),
    "hems-tapo-bridge": os.getenv("MQTT_PASS_TAPO", "hems_tapo_dev"),
    "hems-news": os.getenv("MQTT_PASS_NEWS", "hems_news_dev"),
    "hems-perception": os.getenv("MQTT_PASS_PERCEPTION", "hems_perception_dev"),
    "hems-iot": os.getenv("MQTT_PASS_IOT", "hems_iot_dev"),
}


# Scenarios: (user, forbidden_topic, operation)
# operation is "publish" or "subscribe"
_ACL_DENY_SCENARIOS: list[tuple[str, str, str]] = [
    # hems-backend must NOT publish to arbitrary hems/# outside its allowlist
    ("hems-backend", "hems/brain/reload-character", "publish"),
    ("hems-backend", "hems/personal/biometrics/steps", "publish"),
    # hems-voice must NOT publish anywhere (read-only on hems/brain/#)
    ("hems-voice", "hems/brain/speak", "publish"),
    ("hems-voice", "hems/sensors/living/sensor/co2/value", "publish"),
    # hems-ha-bridge must NOT publish to hems/personal/# or hems/pc/#
    ("hems-ha-bridge", "hems/personal/biometrics/heart_rate", "publish"),
    ("hems-ha-bridge", "hems/pc/cpu", "publish"),
    # hems-biometric must NOT publish outside hems/personal/biometrics/#
    ("hems-biometric", "hems/home/living/light/bulb/state", "publish"),
    ("hems-biometric", "hems/pc/cpu", "publish"),
    # hems-gas must NOT publish outside hems/gas/#
    ("hems-gas", "hems/personal/biometrics/heart_rate", "publish"),
    ("hems-gas", "hems/home/bedroom/light/lamp/state", "publish"),
    # hems-obsidian must NOT publish outside hems/personal/notes/#
    ("hems-obsidian", "hems/gas/calendar/upcoming", "publish"),
    ("hems-obsidian", "hems/pc/cpu", "publish"),
    # hems-openclaw must NOT publish outside hems/pc/# and hems/services/#
    ("hems-openclaw", "hems/personal/biometrics/steps", "publish"),
    ("hems-openclaw", "hems/home/living/light/bulb/state", "publish"),
    # hems-switchbot must NOT write to hems/personal/# or hems/sensors/#
    ("hems-switchbot", "hems/personal/notes/diary", "publish"),
    ("hems-switchbot", "hems/sensors/living/sensor/co2/value", "publish"),
    # hems-tapo-bridge must NOT publish outside hems/tapo/#
    ("hems-tapo-bridge", "hems/home/living/light/bulb/state", "publish"),
    ("hems-tapo-bridge", "hems/personal/biometrics/steps", "publish"),
    # hems-news must NOT publish outside hems/news/#
    ("hems-news", "hems/personal/notes/diary", "publish"),
    ("hems-news", "hems/home/living/light/bulb/state", "publish"),
    # hems-perception must NOT publish outside hems/sensors/+/camera|activity/# and hems/perception/#
    ("hems-perception", "hems/personal/biometrics/heart_rate", "publish"),
    ("hems-perception", "hems/gas/calendar/upcoming", "publish"),
    # hems-iot (sensor devices) must NOT publish to hems/# directly
    ("hems-iot", "hems/brain/reload-character", "publish"),
    ("hems-iot", "hems/personal/biometrics/steps", "publish"),
]


# ---------------------------------------------------------------------------
# Fixture: paho mqtt client factory
# ---------------------------------------------------------------------------


@pytest.fixture
def mqtt_client_factory():
    """Return a factory that creates authenticated paho MQTT clients.

    Each returned client connects synchronously and is disconnected on teardown.
    The fixture itself just imports paho — the ``_skip_if_no_broker`` call must
    happen inside individual tests so the skip reason is accurate.
    """
    paho = pytest.importorskip("paho.mqtt.client", reason="paho-mqtt not installed")

    clients = []

    def _make(username: str, password: str):
        client = paho.Client(client_id=f"test-{username}-{uuid.uuid4().hex[:8]}")
        client.username_pw_set(username, password)
        clients.append(client)
        return client

    yield _make

    for c in clients:
        try:
            c.disconnect()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Core helper: attempt publish and check broker ACL response
# ---------------------------------------------------------------------------


def _publish_and_check_rc(
    client_factory,
    username: str,
    password: str,
    topic: str,
) -> int | None:
    """Connect as *username*, attempt to publish to *topic*, return the rc.

    Mosquitto with ACL enforced returns rc=1 (connection refused) when auth
    fails, or rc=0 but the message is silently dropped / PUBACK withheld when
    ACL denies a publish.

    Returns None when the broker is unreachable (causes test skip).
    """
    import paho.mqtt.client as paho

    received_rc = []
    connected = []

    def on_connect(client, userdata, flags, rc, properties=None):
        connected.append(rc)

    def on_publish(client, userdata, mid):
        # only fires on successful broker ACK
        received_rc.append(0)

    client = paho.Client(client_id=f"test-{username[:12]}-{uuid.uuid4().hex[:6]}")
    client.username_pw_set(username, password)
    client.on_connect = on_connect
    client.on_publish = on_publish

    try:
        client.connect(MQTT_HOST, MQTT_PORT, keepalive=5)
    except OSError:
        return None  # broker unreachable

    client.loop_start()
    deadline = time.monotonic() + _TIMEOUT
    while not connected and time.monotonic() < deadline:
        time.sleep(0.05)
    client.loop_stop()

    if not connected:
        return None  # timed out

    conn_rc = connected[0]

    if conn_rc != 0:
        # Authentication itself failed (bad password, not ACL)
        try:
            client.disconnect()
        except Exception:
            pass
        return conn_rc

    # Connected — attempt publish, wait briefly for PUBACK
    client.loop_start()
    msg_info = client.publish(topic, payload="acl-test", qos=1, retain=False)
    deadline = time.monotonic() + _TIMEOUT
    while not msg_info.is_published() and time.monotonic() < deadline:
        time.sleep(0.05)
    client.loop_stop()

    try:
        client.disconnect()
    except Exception:
        pass

    # is_published() True means broker acknowledged the publish.
    # ACL-denied publishes either: never get PUBACK (QoS 1) or
    # Mosquitto ≥ 2.0 sends a DISCONNECT with reason code 135 (Not authorized).
    return 0 if msg_info.is_published() else 135  # 135 = MQTT Not Authorized


# ---------------------------------------------------------------------------
# Parametrised test
# ---------------------------------------------------------------------------


@pytest.mark.integration
@pytest.mark.parametrize("username,topic,operation", _ACL_DENY_SCENARIOS)
def test_mqtt_acl_rejects_forbidden_publish(username, topic, operation, mqtt_client_factory):
    """Service user must NOT be able to publish to a forbidden topic.

    The test skips if:
    - The broker is unreachable (CI without Docker).
    - paho-mqtt is not installed.
    - The password for the user is not configured (unknown in test env).
    """
    _skip_if_no_broker()

    if operation != "publish":
        pytest.skip(f"Subscribe ACL test not implemented yet (scenario: {username}/{topic})")

    password = _DEFAULT_PASSWORDS.get(username)
    if not password:
        pytest.skip(f"No password configured for {username}")

    rc = _publish_and_check_rc(mqtt_client_factory, username, password, topic)

    if rc is None:
        pytest.skip(f"Broker unreachable or timed out while testing {username} → {topic}")

    # rc == 0 and PUBACK received means the broker accepted the publish — FAIL
    # rc != 0 or no PUBACK means the broker rejected it — PASS
    assert rc != 0, (
        f"Broker accepted forbidden publish: user={username!r} topic={topic!r} "
        f"(rc={rc}). Check infra/mosquitto/aclfile — the ACL may be missing or "
        f"the broker may be running without ACL enforcement."
    )
