#!/usr/bin/env python3
"""
check_env_compose.py — env.example ↔ docker-compose.yml cross-check.

Detects:
  (a) Variables referenced as ${VAR} or ${VAR:-...} in compose that are not
      documented in env.example.
  (b) Uncommented/commented variable assignments in env.example that are not
      used in compose (informational; flagged as WARN unless --strict is given).

Exit codes:
  0  — no errors (warnings do not affect exit code unless --strict)
  1  — at least one undocumented compose variable found (or warnings in --strict)

Run locally:
  python infra/scripts/check_env_compose.py
  python infra/scripts/check_env_compose.py --strict   # treat WARNs as errors
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths (resolved relative to repo root, so the script works from any cwd)
# ---------------------------------------------------------------------------
_REPO = Path(__file__).resolve().parents[2]
_COMPOSE = _REPO / "infra" / "docker-compose.yml"
_ENV_EXAMPLE = _REPO / "env.example"

# ---------------------------------------------------------------------------
# (a) Compose vars intentionally absent from env.example
#
# Add a variable here only if it is:
#   • Hardcoded per-service (not user-configurable), OR
#   • Injected by the Docker/Compose runtime itself, OR
#   • An alias/computed value derived at container startup, OR
#   • A volume-bind path set inside compose (not a user env setting)
# ---------------------------------------------------------------------------
COMPOSE_ONLY_OK = frozenset(
    {
        # Internal service URLs wired by compose (not user-exposed)
        "BACKEND_URL",
        "BRAIN_CHAT_URL",
        "OLLAMA_HOST",
        # Hardcoded per-service values
        "MQTT_BROKER",
        "MQTT_PORT",
        "PORT",                        # fixed to 8000 in each service
        # Volume path tokens set inside compose definitions
        "BIOMETRIC_DB_PATH",
        "EMBEDDING_CACHE_DIR",         # fixed path inside container
        # HA integration: openclaw reads HA via HEMS_HA_* while ha-bridge reads
        # via bare HA_URL/HA_TOKEN. The HEMS_HA_* pair is an openclaw-only
        # interface; env.example documents the canonical HA_* form. These are
        # pending env.example sync (W4.1).
        "HEMS_HA_URL",
        "HEMS_HA_TOKEN",
        # Zigbee2MQTT internal config keys (z2m reads its own env namespace)
        "ZIGBEE2MQTT_CONFIG_MQTT_USER",
        "ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD",
        # Bind-host MQTT address — optional, documented in env.example as a comment
        # but the regex only matches "VAR=" lines; the env.example comment uses
        # "# MQTT_BIND_ADDR=127.0.0.1" which IS matched, but MQTT_BIND_ADDR
        # appears in compose ports: not environment: so it won't show up in
        # compose_vars — no action needed. Listed here for clarity.
    }
)

# Regex for Zigbee2MQTT config vars (all z2m-internal, skip wholesale)
_Z2M_PREFIX = re.compile(r"^ZIGBEE2MQTT_CONFIG_")

# ---------------------------------------------------------------------------
# (b) env.example vars intentionally absent from compose environment: blocks
#
# Add a variable here only if it is:
#   • A volume bind-source path (used in volumes: not environment:)
#   • A Compose CLI meta-var (read by compose itself, not forwarded to containers)
#   • A brain-internal threshold read via Python os.getenv() but not yet
#     forwarded via compose environment: (pending W2.1 / W4.1 compose sync)
#   • A future/placeholder var for features not yet implemented
#   • A deprecated alias intentionally removed from compose
# ---------------------------------------------------------------------------
ENV_ONLY_OK = frozenset(
    {
        # ── Volume bind-source paths ──────────────────────────────────────
        "OBSIDIAN_VAULT_PATH",
        "KNOWLEDGE_SOURCE_PWS",
        "HEMS_HA_CONFIG_PATH",
        "HEMS_MATTER_DATA_PATH",

        # ── Docker Compose CLI meta-vars ──────────────────────────────────
        # These are consumed by the compose CLI itself, not forwarded to
        # container environment: blocks.
        "COMPOSE_PROJECT_NAME",
        "COMPOSE_FILE",
        "COMPOSE_PROFILES",

        # ── Cloud / external service keys (no compose service consumes them
        #    directly — users configure the relevant bridge instead) ────────
        "OPENAI_API_KEY",
        "ANTHROPIC_API_KEY",

        # ── GPU overlay vars (handled by docker-compose.gpu.yml, not
        #    base compose — generated by infra/scripts/gpu_setup.py) ────────
        "GPU_NAME",
        "GPU_VRAM_MB",

        # ── Brain-internal threshold/tune vars (pending compose forwarding)
        #    The brain service reads these via os.getenv() but they are not
        #    yet listed in the compose environment: block.  W4.1 will add
        #    the env.example entries; a future compose sync pass will add
        #    forwarding.  Listed here to avoid noise until that work lands.
        "HEMS_THRESHOLD_CO2_HIGH",
        "HEMS_THRESHOLD_CO2_CRITICAL",
        "HEMS_THRESHOLD_TEMP_HIGH",
        "HEMS_THRESHOLD_TEMP_LOW",
        "HEMS_THRESHOLD_HUMIDITY_HIGH",
        "HEMS_THRESHOLD_HUMIDITY_LOW",
        "HEMS_THRESHOLD_SEDENTARY_MINUTES",
        "HEMS_THRESHOLD_PC_CPU_HIGH",
        "HEMS_THRESHOLD_PC_MEMORY_HIGH",
        "HEMS_THRESHOLD_PC_GPU_TEMP_HIGH",
        "HEMS_THRESHOLD_PC_DISK_HIGH",
        "HEMS_THRESHOLD_SCREEN_TIME_MINUTES",
        "HEMS_THRESHOLD_POWER_IDLE_WATTS",
        "HEMS_THRESHOLD_PM25_HIGH",
        "HEMS_THRESHOLD_PM25_NATIVE",       # deprecated alias
        "HEMS_THRESHOLD_SOIL_LOW",
        "HEMS_THRESHOLD_VOC_HIGH",
        "HEMS_THRESHOLD_PRESSURE_LOW",
        "HEMS_THRESHOLD_LIGHT_LOW",
        "HEMS_THRESHOLD_LIGHT_HIGH",
        "HEMS_THRESHOLD_HR_HIGH",
        "HEMS_THRESHOLD_HR_LOW",
        "HEMS_THRESHOLD_HR_CRITICAL_SLEEP",
        "HEMS_THRESHOLD_SPO2_LOW",
        "HEMS_THRESHOLD_SPO2_CRITICAL_LOW",
        "HEMS_THRESHOLD_STRESS_HIGH",
        "HEMS_THRESHOLD_HRV_LOW",
        "HEMS_THRESHOLD_BODY_TEMP_HIGH",
        "HEMS_THRESHOLD_RESPIRATORY_RATE_HIGH",
        "HEMS_THRESHOLD_TEMP_CRITICAL_HIGH",
        "HEMS_THRESHOLD_TEMP_CRITICAL_LOW",
        "HEMS_ENV_STALE_SEC",
        "HEMS_ZONE_BLIND_SEC",
        "HEMS_PROC_CPU_HIGH",
        "HEMS_PROC_CPU_SUSTAIN_S",
        "HEMS_PROC_MEM_HIGH_GB",
        "HEMS_PROC_COOLDOWN_S",
        "HEMS_PROC_HEAVY_EXCLUDE",
        "HEMS_DEVICE_BATTERY_LOW",
        "HEMS_DEVICE_LQI_LOW",
        "HEMS_DEVICE_STALE_HOURS",
        "HEMS_ENABLE_AUTO_WATER",
        "HEMS_AUTO_WATER_DURATION_S",
        "HEMS_VOC_SUSTAIN_SECONDS",
        "HEMS_VOC_COOLDOWN_SECONDS",
        "HEMS_PRESSURE_LOW_SUSTAIN_S",
        "HEMS_LIGHT_LOW_SUSTAIN_S",
        "HEMS_LIGHT_HIGH_SUSTAIN_S",
        "HEMS_ABSENCE_LIGHTING_ENABLED",
        "HEMS_ABSENCE_LIGHTING_INTERVAL",
        "HEMS_ABSENCE_LIGHTING_HOURS_START",
        "HEMS_ABSENCE_LIGHTING_HOURS_END",
        "HEMS_CIRCADIAN_ENABLED",
        "HEMS_CIRCADIAN_INTERVAL",
        "HEMS_BIOMETRIC_STALE_MINUTES",

        # ── Brain feature flags not yet in compose environment: block ──────
        "PERSONA_REWRITE_ENABLED",
        "PERSONA_REWRITE_CACHE_TTL",
        "AUTOMATION_ENGINE_ENABLED",
        "WAKE_DETECT_HOUR_START",
        "WAKE_DETECT_HOUR_END",
        "BOOT_LOAD_CACHE_DIR",
        "BOOT_LOAD_MAX_TOKENS",
        "BOOT_LOAD_NEWS_STALE_HOURS",       # alias: env.example NEWS_REFRESH_STALE_HOURS
        "NEWS_REFRESH_STALE_HOURS",
        "BRAIN_CHAT_PORT",

        # ── Mobile companion / security ───────────────────────────────────
        "MOBILE_DEVICE_KEY_BYTES",
        "MOBILE_HMAC_SECRET_BYTES",
        "BACKEND_PUBLIC_URL",
        "CHARACTER_VERSION",
        "WEBHOOK_REPLAY_STRICT",

        # ── Internal service URLs documented in env.example but wired by compose
        "VOICE_SERVICE_URL",

        # ── Bridge-internal vars read by Python code but not forwarded via compose
        "OBSIDIAN_MAX_SEARCH_RESULTS",

        # ── MQTT user (compose hardcodes hems; documented for custom setups)
        "MQTT_USER",

        # ── Rate limiting (read by backend at startup, not in compose yet)
        "CHAT_RATE_LIMIT_CAPACITY",
        "CHAT_RATE_LIMIT_REFILL",

        # ── Biometric alternative paths ───────────────────────────────────
        "HUAMI_ENABLED",
        "HUAMI_AUTH_TOKEN",
        "HUAMI_USER_ID",
        "HUAMI_SERVER_REGION",
        "HUAMI_POLL_INTERVAL",
        "BIOMETRIC_DEDUP_WINDOW",

        # ── STT internals ─────────────────────────────────────────────────
        "STT_MODEL_DIR",

        # ── VLM internals not yet in compose ─────────────────────────────
        "VLM_IMAGE_MAX_SIZE",

        # ── Future / phase-2 placeholder vars (data-bridge) ──────────────
        "GOOGLE_CALENDAR_CREDENTIALS",
        "STRAVA_CLIENT_ID",
        "STRAVA_CLIENT_SECRET",
        "FITBIT_CLIENT_ID",
        "FITBIT_CLIENT_SECRET",
        "GARMIN_USERNAME",
        "GARMIN_PASSWORD",
        "INTERVALS_ICU_API_KEY",
        "INTERVALS_ICU_ATHLETE_ID",
        "MIBAND_MODE",

        # ── Brain cycle / power-mode tuning ──────────────────────────────
        "HEMS_NORMAL_HEARTBEAT_INTERVAL",
        "HEMS_NORMAL_CYCLE_INTERVAL",
        "HEMS_LOW_POWER_SLEEP_INTERVAL",
        "HEMS_LOW_POWER_SLEEP_MIN_INTERVAL",
        "HEMS_LOW_POWER_AWAY_INTERVAL",
        "HEMS_LOW_POWER_AWAY_MIN_INTERVAL",
        "HEMS_LOW_POWER_LLM_COOLDOWN",
        "HEMS_LOW_POWER_AWAY_CONFIRM",
        "HEMS_MANUAL_OVERRIDE_DURATION",
        "HEMS_EXTERNAL_URL",

        # ── Task reminder / schedule learner tuning ────────────────────────
        "REMINDER_INTERVAL_MINUTES",
        "REMINDER_COOLDOWN_MINUTES",
        "REMINDER_CHECK_INTERVAL_SECONDS",
        "SCHEDULE_STATE_PATH",
        "TRAVEL_TIMES_JSON",
        "TRAVEL_DEFAULT_MIN",

        # ── Automation engine tuning ───────────────────────────────────────
        "AUTOMATION_EVAL_INTERVAL",
        "AUTOMATION_REFRESH_INTERVAL",
        "AUTOMATION_LLM_REVIEW_TIMEOUT",

        # ── Fatigue model weights ─────────────────────────────────────────
        "FATIGUE_HR_WEIGHT",
        "FATIGUE_HRV_WEIGHT",
        "FATIGUE_SLEEP_WEIGHT",
        "FATIGUE_STRESS_WEIGHT",

        # ── Biometric alternative path (Zepp / Huami direct) ─────────────
        "ZEPP_ENABLED",
        "ZEPP_EMAIL",
        "ZEPP_PASSWORD",
        "ZEPP_POLL_INTERVAL",

        # ── Sunrise alarm fine-tuning (not yet in compose) ───────────────
        "SUNRISE_ALARM_MAX_BRIGHTNESS",
        "SUNRISE_ALARM_MIN_BRIGHTNESS",
        "SUNRISE_ALARM_STEP_SEC",

        # ── TTS backend URL variants ──────────────────────────────────────
        "AIVOICE_URL",          # AI Voice SSML variant; voice-service reads via os.getenv

        # ── Internal URL aliases (not user-facing in compose) ─────────────
        "BACKEND_URL",          # compose uses a hardcoded value; env.example documents
                                # it for reference only
        "DASHBOARD_API_URL",    # same
        "BIOMETRIC_DB_PATH",    # bridge-side path (hardcoded in compose)

        # ── App data directory ────────────────────────────────────────────
        "DATA_DIR",             # hardcoded to /app/data in compose volumes

        # ── Misc ──────────────────────────────────────────────────────────
        "POSTGRES_USER",        # compose uses ${POSTGRES_USER:-hems}; listed
                                # defensively (no-op if already in compose_vars).
        "LLM_NUM_CTX",          # baked into Modelfile; comment-only in env.example
        "MQTT_BROKER",          # documented in env.example but hardcoded per-service
        "MQTT_PORT",            # same
        "HSA_OVERRIDE_GFX_VERSION",  # GPU overlay; forwarded only in gpu compose file
        "EMBEDDING_CACHE_DIR",  # hardcoded to /app/data/embeddings inside container
    }
)


def _extract_compose_vars(compose_text: str) -> set[str]:
    """Return all ${VAR}, ${VAR:-default}, ${VAR:?err} variable names from compose."""
    return {
        m.group(1)
        for m in re.finditer(r"\$\{([A-Z][A-Z0-9_]*)[^}]*\}", compose_text)
    }


def _extract_env_vars(env_text: str) -> set[str]:
    """Return variable names declared in env.example (commented or uncommented)."""
    return {
        m.group(1)
        for line in env_text.splitlines()
        for m in [re.match(r"^\s*#?\s*([A-Z][A-Z0-9_]*)=", line)]
        if m
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 on warnings (env.example-only vars) as well as errors.",
    )
    args = parser.parse_args(argv)

    compose_text = _COMPOSE.read_text()
    env_text = _ENV_EXAMPLE.read_text()

    compose_vars = _extract_compose_vars(compose_text)
    env_vars = _extract_env_vars(env_text)

    # ── (a) compose vars missing from env.example ─────────────────────────
    missing_from_env = sorted(
        v
        for v in compose_vars
        if v not in env_vars
        and v not in COMPOSE_ONLY_OK
        and not _Z2M_PREFIX.match(v)
    )

    # ── (b) env.example vars not referenced in compose (informational) ────
    unused_in_compose = sorted(
        v
        for v in env_vars
        if v not in compose_vars
        and v not in ENV_ONLY_OK
    )

    # ── Report ────────────────────────────────────────────────────────────
    ok = True

    if missing_from_env:
        ok = False
        print(
            f"[ERROR] {len(missing_from_env)} compose variable(s) not documented "
            f"in env.example:"
        )
        for v in missing_from_env:
            print(f"  - {v}")
    else:
        print(
            f"[OK] All {len(compose_vars)} compose variables are documented in "
            f"env.example (or in the known-exclusion list)."
        )

    if unused_in_compose:
        tag = "[ERROR]" if args.strict else "[WARN]"
        if args.strict:
            ok = False
        print(
            f"\n{tag} {len(unused_in_compose)} env.example variable(s) not "
            f"referenced in compose (may be volume-bind sources, future "
            f"placeholders, or compose-forwarding gaps):"
        )
        for v in unused_in_compose:
            print(f"  - {v}")
    else:
        print(
            "[OK] All env.example variables are either used in compose or "
            "in the known-exclusion list."
        )

    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
